name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-java:

    runs-on: ubuntu-latest
    env: 
      status: passed
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: if case
      run: echo "BUILD FAILURE" >> test.txt

    - name: if else deneme
      run: |
        if grep -q "BUILD FAILURE" test.txt; then
          env:
          status: failed
        fi
        echo ${{env.status}}
    - name: Build with Gradle
      run: ./gradlew build
