# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-java:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: if case
      run: echo "BUILD FAILURE" >> test.txt

    - name: if else deneme
      run: |
        if grep -q "BUILD FAILURa" test.txt; then
        echo "Test failed"
        else
        echo "test passed"
        fi

    - name: Build with Gradle
      run: ./gradlew build

    - name: ✨ Send email, you star
      uses: dawidd6/action-send-mail@v1.3.0
      with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_PASSWORD }}
          subject: Your a star ✨
          body: ${{ github.actor }} just starred your mail-on-star repo!!! ${{ github.repository }}
          to: ${{ secrets.BCS_ADDRESS }}
          from: ${{ secrets.GMAIL_ADDRESS }}
